FROM python:3.12
WORKDIR /app

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
git \
ca-certificates \
&& rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -U pip uv

RUN git clone https://github.com/Taxuspt/garmin_mcp
RUN cd /app/garmin_mcp && uv pip install . --system

ENTRYPOINT ["garmin-mcp"]
